### ISSUE TITLE
sync keyword missing in the _set method of zhinst.toolkit.control.drivers.base.daq.DAQModule

### ISSUE THREAD

**Issue by haroldmeerwaldt** [zhinst/zhinst-toolkit#86]
Hi there,

The sync keyword appears to be missing in the _set method of zhinst.toolkit.control.drivers.base.daq.DAQModule. I'm using zhinst-qcodes 0.2.0, zhinst-toolkit 0.2.0, and qcodes 0.28.0.

If I want to set a parameter, I get the following error message:

```
from zhinst.qcodes import UHFLI
uhfli = UHFLI("uhfli_1", "dev2110")
uhfli.daq.grid_cols(100)

Traceback (most recent call last):

  File "C:\Users\haroldm\AppData\Local\Temp/ipykernel_3684/3767187837.py", line 1, in <module>
    uhfli.daq.grid_cols(100)

  File "c:\users\haroldm\repositories\low-level-software\env\lib\site-packages\qcodes\instrument\parameter.py", line 453, in __call__
    self.set(*args, **kwargs)

  File "c:\users\haroldm\repositories\low-level-software\env\lib\site-packages\qcodes\instrument\parameter.py", line 706, in set_wrapper
    raise e

  File "c:\users\haroldm\repositories\low-level-software\env\lib\site-packages\qcodes\instrument\parameter.py", line 690, in set_wrapper
    set_function(raw_val_step, **kwargs)

  File "c:\users\haroldm\repositories\low-level-software\env\lib\site-packages\qcodes\utils\command.py", line 180, in __call__
    return self.exec_function(*args)

  File "c:\users\haroldm\repositories\low-level-software\env\lib\site-packages\zhinst\toolkit\control\node_tree.py", line 350, in __call__
    return self._setter(value, sync)

  File "c:\users\haroldm\repositories\low-level-software\env\lib\site-packages\zhinst\toolkit\control\node_tree.py", line 204, in _setter
    self._device._set(self._path, value, sync=sync)
TypeError: ("_set() got an unexpected keyword argument 'sync'", 'setting uhfli_1_daq_grid_cols to 100')
```

If I take a look at the method, the sync keyword is indeed not there:
```
def _set(self, *args):
    if self._module is None:
        _logger.error(
            "This DAQ is not connected to a dataAcquisitionModule!",
            _logger.ExceptionTypes.ToolkitConnectionError,
        )
    return self._module.set(*args, device=self._parent.serial)
```

I was hoping you could take a look at this.

Sincerely,

Harold

**Comment by tobiasah** [comment]
Hi @haroldmeerwaldt 
thank you for raising this issue. 

might I ask which toolkit version you have installed?

Because in the latest version 0.2.0 it should be there
https://github.com/zhinst/zhinst-toolkit/blob/db4ee3b2944a7274825a9a743badfb812322df6f/src/zhinst/toolkit/control/node_tree.py#L153

**Comment by haroldmeerwaldt** [comment]
Hi @tobiasah,

I indeed have the latest zhinst-toolkit version (0.2.0). I think the error comes from the _set method of zhinst.toolkit.control.drivers.base.daq.DAQModule not having the sync keyword. In line 204 of _setter of Parameter, you can see that it passes the sync keyword.

```
self._device._set(self._path, value, sync=sync)
```

**Comment by tobiasah** [comment]
You are absolutely right the DAQ and Sweeper module somehow got forgotten when adding the sync command.

Unfortunately this will take more than a couple of minutes to fix. I will try to fix this next week.

In the mean time if you could use the branch`missing_sync_daq_scope` from the toolkit that I have created.
https://github.com/zhinst/zhinst-toolkit/tree/tobiasa/missing_sync_daq_scope
(See https://github.com/zhinst/zhinst-toolkit/commit/9783ee8532a9a355b6189b427cabf46d9d71cb2d)

This is just a temporary fix that simply ignores the sync command in the two modules. For sure this is not ideal but it does the trick (since the sync command was not in older toolkit versions it should not break anything)


I will come back to you as soon as possible with a proper fix.

**Comment by tobiasah** [comment]
Since the two modules do not support sync at the moment (even in our core Python API) we have decided to "swallow" the sync argument for now. 

We have already published a patch release with this change so you should be able to update you zhinst-toolkit package.

I hope this solves you problem. If not feel free to reopen it at any time

**Comment by haroldmeerwaldt** [comment]
Perfectly fine solution for me. Thanks for the fast action!
